name: Deployment via ssh/sftp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 21.1.0
      uses: actions/setup-node@v3
      with:
        node-version: 21.1.0

    - name: Build
      run: |
        CI=false
        npm install
        npm run build
      
    - name: Deploy
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ vars.SSH_HOST }}
        DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}
      run: | 
        ssh $SSH_USERNAME@$SSH_HOST mkdir test
        $SSH_PASSWORD
        scp -r ./build/* $SSH_USERNAME@$SSH_HOST:$DEPLOY_PATH
        $SSH_PASSWORD
