name: Deployment via ssh/sftp

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 21.1.0
      uses: actions/setup-node@v3
      with:
        node-version: 21.1.0

    - name: Build
      run: |
        CI=false
        npm install
        npm run build
      
    - name: Deploy
      run: | 
        sshpass -p "$SSH_PASSWORD" ssh $SSH_USER@$SSH_HOST
